global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'flask'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):\d+'
        replacement: '$1'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'health-checks'
    metrics_path: '/health'
    static_configs:
      - targets:
        - 'app:5000'
        - 'nginx:80'
        - 'prometheus:9090'
        - 'grafana:3000'